### ISSUE TITLE
Add TypeScript declarations

### ISSUE THREAD

**Issue by bakatrouble** [cdtinney/react-double-marquee#13]
I've written an external declaration for this module, maybe you want to include it in the package:
```typescript
interface MarqueeProps {
    speed?: number;
    delay?: number;
    direction?: 'right' | 'left';
    childMargin?: number;
    children?: React.ReactNode | React.ReactNode[];
}

declare module 'react-double-marquee' {
    export default class Marquee extends React.PureComponent<MarqueeProps, any> {}
}
```

**Comment by cdtinney** [comment]
Thanks for this! I'll add it to the package - is it expected to be in a path like `react-double-marquee/types`?

**Comment by bakatrouble** [comment]
From what I see in other packages, an `index.d.ts` file in the root of the package (without `declare module ...` block, just `export default ...`) will be enough
![image](https://user-images.githubusercontent.com/7340354/81702681-4603e900-9474-11ea-9137-1327b7d951e3.png)

**Comment by bakatrouble** [comment]
Complete file content would be as follows:
```typescript
import * as React from 'react';

interface MarqueeProps {
    speed?: number;
    delay?: number;
    direction?: 'right' | 'left';
    childMargin?: number;
    children?: React.ReactNode | React.ReactNode[];
}

export default class Marquee extends React.PureComponent<MarqueeProps, any> {}
```

**Comment by cdtinney** [comment]
@bakatrouble Submitted a PR, mind taking a look? Not sure it will work..

**Comment by dalbitresb12** [comment]
Hi @cdtinney.

I'm still getting this on VS Code:

> Could not find a declaration file for module 'react-double-marquee'.

I've seen the repository, but there is no declaration file, even though #16 was merged.
