### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientWidth' of null

### ISSUE THREAD

**Issue by matheusgrieger** [cdtinney/react-double-marquee#17]
I'm on the latest version, using Next.js. When navigating out of the page where this component is mounted, this error is thrown. Also when refreshing/hot-reloading it also throws the same error.

**Comment by cdtinney** [comment]
Do you have the full stack trace? I think I've fixed it, but would like to verify.

EDIT: trying to update the testing libraries to see if I can test this, but (previously) I wasn't able to due to `jsdom` not supporting the method I'm using to update the elements (specifically using `clientWidth`).
