### ISSUE TITLE
Component does not update or unmount

### ISSUE THREAD

**Issue by aaadamgo** [cdtinney/react-double-marquee#25]
Have this on a couple of websites using Gatsby. And if you resize the browser or change page, I get multiple console errors saying;

1. Cannot read property 'clientWidth' of null
2. Cannot read property 'style' of null

Any ideas on how to resolve?

**Comment by joebentaylor1995** [comment]
I get this error too on www.makebeautifulwork.com - surely theres a fix for this?

**Comment by joebentaylor1995** [comment]
Duplicate of #8

**Comment by cdtinney** [comment]
I don't really have time to try again at fixing this but if anyone has a fix, happy to review a PR.

**Comment by joebentaylor1995** [comment]
Another package it is then, little bit disappointing to be honest 

Kind regards,

Joe

**Comment by cdtinney** [comment]
Can you both try 1.0.6? May have fixed it.

**Comment by aaadamgo** [comment]
Just quickly tested this locally and it seems to be fixed. I'll run a production build tomorrow.

**Comment by joebentaylor1995** [comment]
Hes only gone and done it @cdtinney . Legend.
