### ISSUE TITLE
Show child text twice for direction="left"

### ISSUE THREAD

**Issue by Kstar0722** [cdtinney/react-double-marquee#26]
it works well in long text, but it shows child text twice for direction as left with short text
![Screen Shot 2020-10-13 at 7 17 48 AM](https://user-images.githubusercontent.com/29844835/95872987-4efb2e00-0d24-11eb-9d6a-1bcb2c461b76.png)

is there any solution?

**Comment by cdtinney** [comment]
We'd need a PR to address this, same issue as #19 I believe. Open to PRs here.
