### ISSUE TITLE
There is a way to make the text move from right to left?

### ISSUE THREAD

**Issue by victoralvesf** [cdtinney/react-double-marquee#6]
Hi, thanks for this package. I'm using it, but at NPM docs, there's nothing about setting the movement. Is that possible?

**Comment by cdtinney** [comment]
Not at the moment, will try to work on this.

**Comment by victoralvesf** [comment]
Thanks for the answer.

**Comment by cdtinney** [comment]
@victoralvesf this has been added in v1.0.1 that's published now! Let me know if there are any issues.

**Comment by victoralvesf** [comment]
@cdtinney Thanks for this release, if i find any issues i'll let you know about it.
