### ISSUE TITLE
Doesnt unmount

### ISSUE THREAD

**Issue by joebentaylor1995** [cdtinney/react-double-marquee#8]
same as title, component doesnt mount on page change

**Comment by cdtinney** [comment]
Hi - can you provide reproduction steps? I'm not sure this is an issue with this component, there is no cleanup that needs to be done on unmounting. React handles mounting/unmounting of components.

**Comment by joebentaylor1995** [comment]
Hi @cdtinney I can show you directly if you want to organise a call with me through joebentaylor1995@icloud.com or take a look at this test site:
[Click here](https://app.netlify.com/sites/levinriegnertest/deploys/5ecd0ade7ec74b0006cb2765)

**Comment by cdtinney** [comment]
@joebentaylor1995 The site requires login. Can you try updating to `v1.0.5`? Are there any errors in `console`? Can you take a screen video?

**Comment by joebentaylor1995** [comment]
Sorry I meant this address:
[Click here](https://levinriegnertest.netlify.app/home)

When youre on mobile change pages and you'll see the error.

Ill try updating and see what happens

**Comment by joebentaylor1995** [comment]
error is:
https://i.imgur.com/cYapG7W.png

**Comment by cdtinney** [comment]
Should be fixed - https://github.com/cdtinney/react-double-marquee/pull/18

Let me know if updating does the trick.

**Comment by joebentaylor1995** [comment]
@cdtinney This has not been fixed please see
[Latest issue from another person](https://github.com/cdtinney/react-double-marquee/issues/25)
